
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
  # Name of the location where Home Assistant is running

homeassistant:
  name: Bergerud Casa
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_loc_home
  longitude: !secret longitude_loc_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 50
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Oslo

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

volvooncall: !include volvo.yaml
fibaro: !include fibaro.yaml
climate: !include climate.yaml

device_tracker:
  - platform: linksys_velop
    host: 192.168.1.1
    username: admin
    password: !secret velop_password

