version: '3'
services:
        homeassistant:
                container_name: homeassistant
                image: homeassistant/home-assistant:stable 
                ports:
                        - "8123:8123"
                volumes:
                        - /home/oyvind/src/Home-AssistantConfig:/config
                        - /etc/localtime:/etc/localtime:ro
                restart: unless-stopped
                network_mode: host
